### ISSUE TITLE
Packages view

### ISSUE THREAD

**Issue by budjizu** [zaffre/zaffre-modx#2]
Reads directory /assets/components/zaffre/packages (*.log and *.zip)
Show 
ID | Timestamp | Actions

Actions: Buttons - if file .zip (install)/.log (show) | remove

**Comment by Alroniks** [comment]
А как сюда будут загружаться пакеты?
Сейчас есть папка .zaffre. А в папке /assets/components/zaffre/ лежат исходники самого компонента, т.е. пакеты класть лучше в /assets/zaffre/, чтобы при обновлении компонента не происходило затирание. Но в любом случае, непонятно на сейчас, какие данные нужно читать из папки.

**Comment by Alroniks** [comment]
Closed by #6c9d01d4b908625b8c448f3311989314105f7e5b
